name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Run Tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd test
        mkdir artefact
        python -m xmlrunner ./test_piloto.py  -v  --output-file artefact/test.xml

        
    - name: Archive test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test
        path: .\test\artefact\test.xml

    
  notificacao:
    runs-on: ubuntu-latest

    env:
      EMAIL_LIST: caio.lima@ges.inatel.br, vinicius.ximenis@ges.inatel.br, gabriel.augusto@gec.inatel.br, tiago.rodrigues@gec.inatel.br 

    steps:
    - name: Executa comandos
      uses: actions/checkout@v3
    - run: sh scripts/email.sh